language: go
sudo: false

matrix:
  fast_finish: true
  include:
  - go: 1.10.x
  - go: 1.11.x
    env: GO111MODULE=on
  - go: 1.12.x
    env: GO111MODULE=on
  - go: master
    env: GO111MODULE=on

git:
  depth: 10

install:
  - if [[ "${GO111MODULE}" = "on" ]]; then go mod download; else go get -t -v ./...; fi

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
